apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
labels:
  app: mosquitto
data:
  # To create hashed password, replace admin and mystrongmqttpassword and run:
  # docker run --rm -it eclipse-mosquitto:2.0 sh -c "mosquitto_passwd -c -b /pws.txt admin mystrongmqttpassword && cat pws.txt"
  password.txt: |
    admin:$7$101$NU4rOx1ksiolL8X/$z+y64h0Rxar6fOuR/EP1dhKjaMoubGAQrwUjS9oN7AX9yVVor9oU15jrSP2SZPdfooneb3ugG66DfJZb7puYzQ==