apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  ports:
    - port: 1883
      nodePort: 31883
  selector:
    app: mosquitto
    tier: frontend
  type: NodePort